server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leyou
    username: /leyou
    password: leyou
    host: 192.168.19.121

leyou:
  sms:
    accessKeyId: 
    accessKeySecret: 
    signName: 乐优商城
    verifyCodeTemplate: 
